name: Update Fork

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check repo
        run: pwd
        
      - name: Change directory
        run: cd https://github.com/AEAJanGajda/AEAdynamics365smb-docs.git

      - name: Check repo 2
        run: pwd
        
      - name: Add upstream
        run: git remote add upstream https://github.com/MicrosoftDocs/dynamics365smb-docs.git || true

      - name: Fetch changes
        run: git fetch upstream

      - name: Merge changes
        run: git merge upstream/main || exit 0
        
      - name: Push changes
        run: git push origin main


    
