name: Update Fork

on:
  schedule:
    - cron: '52 10 * * 2'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Add Upstream
        run: git remote add upstream https://github.com/MicrosoftDocs/dynamics365smb-docs.git || true

      - name: Fetch changes
        run: git fetch upstream

      - name: Merge changes
        run: git merge upstream/main || exit 0
        
      - name: Push changes
        run: git push origin main


    
