name: Update Fork

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Fetch changes
        run: |
          git remote add upstream https://github.com/MicrosoftDocs/dynamics365smb-docs.git
          git fetch upstream
          
      - name: Merge changes
        run: |
          git checkout main  # or the branch you want to sync
          git merge upstream/main  # or the branch you want to sync from upstream
          git push origin main  # or the branch you want to push to



    
